"""
Created on: 01/02/18
Author: Nikolaos Apostolakos
"""

from __future__ import division, print_function

import abc
import os

from astropy.io import fits

from nnpz.utils.Fits import tableToHdu, columnsToFitsColumn


class OutputHandler(object):


    class OutputColumnProviderInterface(object):
        __metaclass__ = abc.ABCMeta

        @abc.abstractmethod
        def addContribution(self, reference_sample_i, neighbor, flags):
            pass

        @abc.abstractmethod
        def getColumns(self):
            pass


    class OutputExtensionTableProviderInterface(object):
        __metaclass__ = abc.ABCMeta

        @abc.abstractmethod
        def addContribution(self, reference_sample_i, neighbor, flags):
            pass

        @abc.abstractmethod
        def getExtensionTables(self):
            """
            Returns:
                A dictionary with additional astropy.Table, where the key is the table name
            """
            pass


    class HeaderProviderInterface(object):
        __metaclass__ = abc.ABCMeta

        @abc.abstractmethod
        def getHeaderKeywords(self):
            """
            Returns:
                 A map with keys the keyword names and values the header values.
            """
            pass


    def __init__(self):
        self.__column_providers = []
        self.__hdu_providers = []
        self.__header_providers = []


    def addColumnProvider(self, provider):
        self.__column_providers.append(provider)


    def addExtensionTableProvider(self, provider):
        self.__hdu_providers.append(provider)


    def addHeaderProvider(self, provider):
        self.__header_providers.append(provider)


    def addContribution(self, reference_sample_i, neighbor, flags):
        for p in self.__column_providers:
            p.addContribution(reference_sample_i, neighbor, flags)
        for hp in self.__hdu_providers:
            hp.addContribution(reference_sample_i, neighbor, flags)


    def save(self, filename):
        hdu_list = []

        # Primary hdu
        hdr = fits.Header()
        hdr['COMMENT'] = 'Generated by nnpz'
        hdu_list.append(fits.PrimaryHDU(header=hdr))

        # Table with the results
        columns = []
        for prov in self.__column_providers:
            columns.extend(columnsToFitsColumn(prov.getColumns()))
        hdr = fits.Header()
        hdr['COMMENT'] = 'Generated by nnpz'
        for prov in self.__header_providers:
            hdr.update(prov.getHeaderKeywords())
        hdu_list.append(fits.BinTableHDU.from_columns(columns, header=hdr))

        # Extensions
        for hp in self.__hdu_providers:
            for name, table in hp.getExtensionTables().items():
                ext_hdu = tableToHdu(table)
                ext_hdu.name = name
                hdu_list.append(ext_hdu)

        hdul = fits.HDUList(hdu_list)

        if os.path.exists(filename):
            os.remove(filename)
        hdul.writeto(filename)
